# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fcaac9f368326ed65d398d09164ec34807cc6d7cd7a12e406bd3f4e6000e10550af4558070dd006655db17646e5a54f5f0ff414a128902534c0ef55ffcf728bd

test:
  secret_key_base: 83f8d2f07b764a31588ebb3f27531b9dd965eb3c6adaca668b554b22228bb19945476d9d23b48dddad126ba6a094b81694b94401de74178b21dedd3f278c6447

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
